version: '3.6'
services:
  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
    restart: always
    container_name: social-database
    ports:
      - 3306:3306
    env_file:
      - .env.database.local

  web:
    image: lorinc/social-network:1.0.0-SNAPSHOT
    restart: "no"
    container_name: social-network
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env.spring.local
      - .env.database.local